module

/-
Generated by scripts/gen-encoding-data.lean; do not edit by hand. Regenerate with:
  lake env lean --run scripts/gen-encoding-data.lean

Source: iconv (GNU libc) 2.26, one byte at a time, with the generator's two
rows from the encoding's owner (Mac OS Roman 0xC6 and 0xF0). Each table is an
encoding's upper half: the scalar each byte from 0x80 stands for, none where
the encoding has no character. This module carries only data: `Encoding.Legacy.high`
reads it, and its contracts are checked by the suite.
-/

namespace LeanTex.Core.EncodingData

/-- Windows-1252, read for `latin1`, `ansinew` and `cp1252`.
Entry `k` is byte `0x80 + k`. -/
public def windows1252 : Array (Option Char) :=
  #[some '\u20AC', none, some '\u201A', some '\u0192', some '\u201E', some '\u2026',
    some '\u2020', some '\u2021', some '\u02C6', some '\u2030', some '\u0160', some '\u2039',
    some '\u0152', none, some '\u017D', none, none, some '\u2018',
    some '\u2019', some '\u201C', some '\u201D', some '\u2022', some '\u2013', some '\u2014',
    some '\u02DC', some '\u2122', some '\u0161', some '\u203A', some '\u0153', none,
    some '\u017E', some '\u0178', some '\u00A0', some '\u00A1', some '\u00A2', some '\u00A3',
    some '\u00A4', some '\u00A5', some '\u00A6', some '\u00A7', some '\u00A8', some '\u00A9',
    some '\u00AA', some '\u00AB', some '\u00AC', some '\u00AD', some '\u00AE', some '\u00AF',
    some '\u00B0', some '\u00B1', some '\u00B2', some '\u00B3', some '\u00B4', some '\u00B5',
    some '\u00B6', some '\u00B7', some '\u00B8', some '\u00B9', some '\u00BA', some '\u00BB',
    some '\u00BC', some '\u00BD', some '\u00BE', some '\u00BF', some '\u00C0', some '\u00C1',
    some '\u00C2', some '\u00C3', some '\u00C4', some '\u00C5', some '\u00C6', some '\u00C7',
    some '\u00C8', some '\u00C9', some '\u00CA', some '\u00CB', some '\u00CC', some '\u00CD',
    some '\u00CE', some '\u00CF', some '\u00D0', some '\u00D1', some '\u00D2', some '\u00D3',
    some '\u00D4', some '\u00D5', some '\u00D6', some '\u00D7', some '\u00D8', some '\u00D9',
    some '\u00DA', some '\u00DB', some '\u00DC', some '\u00DD', some '\u00DE', some '\u00DF',
    some '\u00E0', some '\u00E1', some '\u00E2', some '\u00E3', some '\u00E4', some '\u00E5',
    some '\u00E6', some '\u00E7', some '\u00E8', some '\u00E9', some '\u00EA', some '\u00EB',
    some '\u00EC', some '\u00ED', some '\u00EE', some '\u00EF', some '\u00F0', some '\u00F1',
    some '\u00F2', some '\u00F3', some '\u00F4', some '\u00F5', some '\u00F6', some '\u00F7',
    some '\u00F8', some '\u00F9', some '\u00FA', some '\u00FB', some '\u00FC', some '\u00FD',
    some '\u00FE', some '\u00FF']

/-- ISO 8859-15, read for `latin9`.
Entry `k` is byte `0x80 + k`. -/
public def iso885915 : Array (Option Char) :=
  #[none, none, none, none, none, none,
    none, none, none, none, none, none,
    none, none, none, none, none, none,
    none, none, none, none, none, none,
    none, none, none, none, none, none,
    none, none, some '\u00A0', some '\u00A1', some '\u00A2', some '\u00A3',
    some '\u20AC', some '\u00A5', some '\u0160', some '\u00A7', some '\u0161', some '\u00A9',
    some '\u00AA', some '\u00AB', some '\u00AC', some '\u00AD', some '\u00AE', some '\u00AF',
    some '\u00B0', some '\u00B1', some '\u00B2', some '\u00B3', some '\u017D', some '\u00B5',
    some '\u00B6', some '\u00B7', some '\u017E', some '\u00B9', some '\u00BA', some '\u00BB',
    some '\u0152', some '\u0153', some '\u0178', some '\u00BF', some '\u00C0', some '\u00C1',
    some '\u00C2', some '\u00C3', some '\u00C4', some '\u00C5', some '\u00C6', some '\u00C7',
    some '\u00C8', some '\u00C9', some '\u00CA', some '\u00CB', some '\u00CC', some '\u00CD',
    some '\u00CE', some '\u00CF', some '\u00D0', some '\u00D1', some '\u00D2', some '\u00D3',
    some '\u00D4', some '\u00D5', some '\u00D6', some '\u00D7', some '\u00D8', some '\u00D9',
    some '\u00DA', some '\u00DB', some '\u00DC', some '\u00DD', some '\u00DE', some '\u00DF',
    some '\u00E0', some '\u00E1', some '\u00E2', some '\u00E3', some '\u00E4', some '\u00E5',
    some '\u00E6', some '\u00E7', some '\u00E8', some '\u00E9', some '\u00EA', some '\u00EB',
    some '\u00EC', some '\u00ED', some '\u00EE', some '\u00EF', some '\u00F0', some '\u00F1',
    some '\u00F2', some '\u00F3', some '\u00F4', some '\u00F5', some '\u00F6', some '\u00F7',
    some '\u00F8', some '\u00F9', some '\u00FA', some '\u00FB', some '\u00FC', some '\u00FD',
    some '\u00FE', some '\u00FF']

/-- Mac OS Roman, read for `applemac`.
Entry `k` is byte `0x80 + k`. -/
public def macRoman : Array (Option Char) :=
  #[some '\u00C4', some '\u00C5', some '\u00C7', some '\u00C9', some '\u00D1', some '\u00D6',
    some '\u00DC', some '\u00E1', some '\u00E0', some '\u00E2', some '\u00E4', some '\u00E3',
    some '\u00E5', some '\u00E7', some '\u00E9', some '\u00E8', some '\u00EA', some '\u00EB',
    some '\u00ED', some '\u00EC', some '\u00EE', some '\u00EF', some '\u00F1', some '\u00F3',
    some '\u00F2', some '\u00F4', some '\u00F6', some '\u00F5', some '\u00FA', some '\u00F9',
    some '\u00FB', some '\u00FC', some '\u2020', some '\u00B0', some '\u00A2', some '\u00A3',
    some '\u00A7', some '\u2022', some '\u00B6', some '\u00DF', some '\u00AE', some '\u00A9',
    some '\u2122', some '\u00B4', some '\u00A8', some '\u2260', some '\u00C6', some '\u00D8',
    some '\u221E', some '\u00B1', some '\u2264', some '\u2265', some '\u00A5', some '\u00B5',
    some '\u2202', some '\u2211', some '\u220F', some '\u03C0', some '\u222B', some '\u00AA',
    some '\u00BA', some '\u03A9', some '\u00E6', some '\u00F8', some '\u00BF', some '\u00A1',
    some '\u00AC', some '\u221A', some '\u0192', some '\u2248', some '\u2206', some '\u00AB',
    some '\u00BB', some '\u2026', some '\u00A0', some '\u00C0', some '\u00C3', some '\u00D5',
    some '\u0152', some '\u0153', some '\u2013', some '\u2014', some '\u201C', some '\u201D',
    some '\u2018', some '\u2019', some '\u00F7', some '\u25CA', some '\u00FF', some '\u0178',
    some '\u2044', some '\u20AC', some '\u2039', some '\u203A', some '\uFB01', some '\uFB02',
    some '\u2021', some '\u00B7', some '\u201A', some '\u201E', some '\u2030', some '\u00C2',
    some '\u00CA', some '\u00C1', some '\u00CB', some '\u00C8', some '\u00CD', some '\u00CE',
    some '\u00CF', some '\u00CC', some '\u00D3', some '\u00D4', some '\uF8FF', some '\u00D2',
    some '\u00DA', some '\u00DB', some '\u00D9', some '\u0131', some '\u02C6', some '\u02DC',
    some '\u00AF', some '\u02D8', some '\u02D9', some '\u02DA', some '\u00B8', some '\u02DD',
    some '\u02DB', some '\u02C7']

end LeanTex.Core.EncodingData
