namespace LeanTex.Core

/-!
Language is data. babel v26.3's own design: a locale is a CLDR-seeded
data record (`babel-<lang>.ini` in TeX Live — captions, date names,
typography, quote delimiters), and adding a language to babel is adding
a data file, no code. This engine copies that shape: `Locale` carries
exactly the fields the engine reads today, with no defaults and no
`Option` — totality is the type, so a locale that cannot caption a
figure is unrepresentable. The shipped records live in `LocaleData.lean`
(generated by `scripts/gen-locale-data.lean` from the babel ini files);
contracts quantify over `Locale.builtin`, never per language.
-/

/-- One language's reader-visible data, keyed by its BCP 47 tag. Every
field is a value the engine reads at a named site: captions at
`Ir.captionPrefix` and the abstract/references furniture, months in the
bibliography, quotes at `\enquote`, hyphenmins at pattern selection. -/
structure Locale where
  /-- BCP 47 language tag (`tag.bcp47` in the ini). -/
  tag : String
  figure : String
  table : String
  abstract : String
  references : String
  /-- The twelve wide month names, January first (`months.wide.*`). -/
  months : Array String
  /-- Outer and inner quote delimiters (`delimiters.quotes`, four
  characters: outer open/close, inner open/close). -/
  quoteOpen : String
  quoteClose : String
  quoteInnerOpen : String
  quoteInnerClose : String
  /-- Hyphenation minima (`lefthyphenmin`/`righthyphenmin`): the shortest
  fragment a break may leave on each side. -/
  leftMin : Nat
  rightMin : Nat
  deriving Repr, BEq

namespace Locale

/-- babel's language option names → BCP 47 tags, for the languages the
engine ships locales for (babel manual §1.3's option tables; the dialect
spellings are babel's own — `ngerman` is the reformed orthography,
`frenchb`/`francais` the historic French option names). A name outside
this list is a language the engine has no record for, named W0368. -/
def babelNames : List (String × String) :=
  [("english", "en"), ("american", "en"), ("USenglish", "en"),
   ("british", "en"), ("UKenglish", "en"), ("canadian", "en"),
   ("australian", "en"), ("newzealand", "en"),
   ("french", "fr"), ("francais", "fr"), ("frenchb", "fr"),
   ("canadien", "fr"), ("acadian", "fr"),
   ("german", "de"), ("germanb", "de"), ("ngerman", "de"),
   ("austrian", "de"), ("naustrian", "de")]

/-- The tag a babel language option names: the option table first, else
the name taken as a BCP 47 tag itself (`\selectlanguage{fr}` is legal
babel since 3.43). -/
def babelTagOf (name : String) : String :=
  (babelNames.lookup name).getD name

end Locale

end LeanTex.Core
