namespace LeanTex.Core

/-!
Language is data. babel v26.3's own design: a locale is a CLDR-seeded
data record (`babel-<lang>.ini` in TeX Live — captions, date names,
typography, quote delimiters), and adding a language to babel is adding
a data file, no code. This engine copies that shape: `Locale` carries
exactly the fields the engine reads today, with no defaults and no
`Option` — totality is the type, so a locale that cannot caption a
figure is unrepresentable. The shipped records live in `LocaleData.lean`
(generated by `scripts/gen-locale-data.lean` from the babel ini files);
contracts quantify over `Locale.builtin`, never per language.
-/

/-- One kind's cleveref names, the four forms its language blocks declare
(cleveref.sty v0.21.4, 2018/03/27): `\crefname{<kind>}{one}{many}` gives
the lowercase pair `\cref`/`\crefrange` read, `\Crefname` the capitalised
pair `\Cref` reads — independent strings, not a case fold: English
abbreviates `\cref{eq}` to "eq." while `\Cref` spells "Equation"
(the package's own defaults, `abbrev` on and `capitalise` off). -/
structure CrefName where
  one : String
  many : String
  capOne : String
  capMany : String
  deriving Repr, BEq

/-- One language's reader-visible data, keyed by its BCP 47 tag. Every
field is a value the engine reads at a named site: captions at
`Ir.captionPrefix` and the abstract/references furniture, months in the
bibliography, quotes at `\enquote`, hyphenmins at pattern selection,
cleveref names and the range conjunction at `Ir.refText`. -/
structure Locale where
  /-- BCP 47 language tag (`tag.bcp47` in the ini). -/
  tag : String
  figure : String
  table : String
  /-- The algorithm float's caption word ("Algorithm 1: …"). Not in the
  babel inis: sourced from algorithm2e's own language options
  (`\algorithmcfname` under `english`/`french`/`german`,
  algorithm2e.sty), carried by the generator's hand-cited table. -/
  algorithm : String
  abstract : String
  references : String
  /-- The twelve wide month names, January first (`months.wide.*`). -/
  months : Array String
  /-- Outer and inner quote delimiters (`delimiters.quotes`, four
  characters: outer open/close, inner open/close). -/
  quoteOpen : String
  quoteClose : String
  quoteInnerOpen : String
  quoteInnerClose : String
  /-- Hyphenation minima (`lefthyphenmin`/`righthyphenmin`): the shortest
  fragment a break may leave on each side. -/
  leftMin : Nat
  rightMin : Nat
  /-- cleveref's names per referencable kind (cleveref.sty v0.21.4
  language blocks — english, german, french — under the package's default
  options; not babel data, so the generator carries the table itself,
  cited there). `crefSection` serves every heading level, as cleveref's
  subsection names are the section's. -/
  crefSection : CrefName
  crefEquation : CrefName
  crefFigure : CrefName
  crefTable : CrefName
  /-- cleveref's algorithm names (cleveref.sty v0.21.4, the english,
  french and german `\crefname{algorithm}` lines — cleveref carries the
  kind itself; algorithm2e aliases its `algocf` counter onto it). -/
  crefAlgorithm : CrefName
  /-- `\crefrange`'s conjunction word (`\crefrangeconjunction` without its
  no-break space: "to", "bis", "à"). -/
  crefRangeTo : String
  /-- The word before a numbered code listing's caption ("Listing 1: …",
  read at `Ir.listingCaption`). Not CLDR data — the babel inis carry no
  listing caption — so the generator embeds its own cited table: English
  is listings' own `\lstlistingname` default (listings.sty,
  `\lst@UserCommand\lstlistingname{Listing}`); French and German are
  cleveref's language definitions (cleveref.sty, `\crefname{listing}`:
  french "Liste", ngerman "Listing"). -/
  listing : String
  /-- The decimal marker (`[numbers] decimal` in the ini, CLDR's number
  symbols): what `\num{1.5}` prints between integer and fraction. -/
  decimal : String
  /-- The digit-group separator `\num` sets every three digits. fr and de
  take the ini's `[numbers] group` (fr U+202F narrow no-break space, de
  "."); en takes the thin space U+2009 — siunitx's own default
  `group-separator = \,` (siunitx manual §"Printing numbers") — rather
  than the ini's ",", which is plain-prose grouping, not the scientific
  spelling `\num` exists for. -/
  group : String
  deriving Repr, BEq

namespace Locale

/-- babel's language option names → BCP 47 tags, for the languages the
engine ships locales for (babel manual §1.3's option tables; the dialect
spellings are babel's own — `ngerman` is the reformed orthography,
`frenchb`/`francais` the historic French option names). A name outside
this list is a language the engine has no record for, named W0368. -/
def babelNames : List (String × String) :=
  [("english", "en"), ("american", "en"), ("USenglish", "en"),
   ("british", "en"), ("UKenglish", "en"), ("canadian", "en"),
   ("australian", "en"), ("newzealand", "en"),
   ("french", "fr"), ("francais", "fr"), ("frenchb", "fr"),
   ("canadien", "fr"), ("acadian", "fr"),
   ("german", "de"), ("germanb", "de"), ("ngerman", "de"),
   ("austrian", "de"), ("naustrian", "de")]

/-- The tag a babel language option names: the option table first, else
the name taken as a BCP 47 tag itself (`\selectlanguage{fr}` is legal
babel since 3.43). -/
def babelTagOf (name : String) : String :=
  (babelNames.lookup name).getD name

end Locale

end LeanTex.Core
