module

/-
Generated by scripts/gen-pygments-style-data.lean; do not edit by hand. Regenerate with:
  lake env lean --run scripts/gen-pygments-style-data.lean

Source: Pygments 2.21.0, each shipped style's `styles` table, every
non-empty declaration verbatim and in token order. This module carries only
data: `PygmentsStyle` resolves it, and the suite holds that resolution to
Pygments' own answers in testdata/oracles/pygments-styles.tsv.
-/

namespace LeanTex.Core.PygmentsStyleData

/-- `pygments.styles.default`'s declarations: (token type, declaration). -/
public def defaultStyle : List (String × String) :=
  [("Token.Comment", "italic #3D7B7B"),
   ("Token.Comment.Preproc", "noitalic #9C6500"),
   ("Token.Error", "border:#FF0000"),
   ("Token.Generic.Deleted", "#A00000"),
   ("Token.Generic.Emph", "italic"),
   ("Token.Generic.EmphStrong", "bold italic"),
   ("Token.Generic.Error", "#E40000"),
   ("Token.Generic.Heading", "bold #000080"),
   ("Token.Generic.Inserted", "#008400"),
   ("Token.Generic.Output", "#717171"),
   ("Token.Generic.Prompt", "bold #000080"),
   ("Token.Generic.Strong", "bold"),
   ("Token.Generic.Subheading", "bold #800080"),
   ("Token.Generic.Traceback", "#04D"),
   ("Token.Keyword", "bold #008000"),
   ("Token.Keyword.Pseudo", "nobold"),
   ("Token.Keyword.Type", "nobold #B00040"),
   ("Token.Literal.Number", "#666666"),
   ("Token.Literal.String", "#BA2121"),
   ("Token.Literal.String.Doc", "italic"),
   ("Token.Literal.String.Escape", "bold #AA5D1F"),
   ("Token.Literal.String.Interpol", "bold #A45A77"),
   ("Token.Literal.String.Other", "#008000"),
   ("Token.Literal.String.Regex", "#A45A77"),
   ("Token.Literal.String.Symbol", "#19177C"),
   ("Token.Name.Attribute", "#687822"),
   ("Token.Name.Builtin", "#008000"),
   ("Token.Name.Class", "bold #0000FF"),
   ("Token.Name.Constant", "#880000"),
   ("Token.Name.Decorator", "#AA22FF"),
   ("Token.Name.Entity", "bold #717171"),
   ("Token.Name.Exception", "bold #CB3F38"),
   ("Token.Name.Function", "#0000FF"),
   ("Token.Name.Label", "#767600"),
   ("Token.Name.Namespace", "bold #0000FF"),
   ("Token.Name.Tag", "bold #008000"),
   ("Token.Name.Variable", "#19177C"),
   ("Token.Operator", "#666666"),
   ("Token.Operator.Word", "bold #AA22FF"),
   ("Token.Text.Whitespace", "#bbbbbb")]

/-- `pygments.styles.friendly`'s declarations: (token type, declaration). -/
public def friendlyStyle : List (String × String) :=
  [("Token.Comment", "italic #60a0b0"),
   ("Token.Comment.Preproc", "noitalic #007020"),
   ("Token.Comment.Special", "noitalic bg:#fff0f0"),
   ("Token.Error", "border:#FF0000"),
   ("Token.Generic.Deleted", "#A00000"),
   ("Token.Generic.Emph", "italic"),
   ("Token.Generic.EmphStrong", "bold italic"),
   ("Token.Generic.Error", "#FF0000"),
   ("Token.Generic.Heading", "bold #000080"),
   ("Token.Generic.Inserted", "#00A000"),
   ("Token.Generic.Output", "#888"),
   ("Token.Generic.Prompt", "bold #c65d09"),
   ("Token.Generic.Strong", "bold"),
   ("Token.Generic.Subheading", "bold #800080"),
   ("Token.Generic.Traceback", "#04D"),
   ("Token.Keyword", "bold #007020"),
   ("Token.Keyword.Pseudo", "nobold"),
   ("Token.Keyword.Type", "nobold #902000"),
   ("Token.Literal.Number", "#40a070"),
   ("Token.Literal.String", "#4070a0"),
   ("Token.Literal.String.Doc", "italic"),
   ("Token.Literal.String.Escape", "bold #4070a0"),
   ("Token.Literal.String.Interpol", "italic #70a0d0"),
   ("Token.Literal.String.Other", "#c65d09"),
   ("Token.Literal.String.Regex", "#235388"),
   ("Token.Literal.String.Symbol", "#517918"),
   ("Token.Name.Attribute", "#4070a0"),
   ("Token.Name.Builtin", "#007020"),
   ("Token.Name.Class", "bold #0e84b5"),
   ("Token.Name.Constant", "#60add5"),
   ("Token.Name.Decorator", "bold #555555"),
   ("Token.Name.Entity", "bold #d55537"),
   ("Token.Name.Exception", "#007020"),
   ("Token.Name.Function", "#06287e"),
   ("Token.Name.Label", "bold #002070"),
   ("Token.Name.Namespace", "bold #0e84b5"),
   ("Token.Name.Tag", "bold #062873"),
   ("Token.Name.Variable", "#bb60d5"),
   ("Token.Operator", "#666666"),
   ("Token.Operator.Word", "bold #007020"),
   ("Token.Text.Whitespace", "#bbbbbb")]

end LeanTex.Core.PygmentsStyleData
