/-
Regenerate LeanTex/Core/EncodingData.lean: the upper halves (bytes 0x80–0xFF)
of the 8-bit encodings an inputenc declaration can name that the engine
reads, each byte's Unicode scalar or none. Run from the repository root with:

  lake env lean --run scripts/gen-encoding-data.lean

Source: the host's iconv, queried one byte at a time; glibc's iconv carries
the Unicode Consortium's mapping tables. The encodings and the inputenc
options that name them:
- WINDOWS-1252: `latin1`, `ansinew`, `cp1252`. The WHATWG Encoding Standard
  reads the label latin1 as windows-1252, whose graphic characters are
  ISO 8859-1's plus the 0x80–0x9F block a file labelled latin1 carries in
  practice (curly quotes, dashes, the euro sign).
- ISO-8859-15: `latin9`.
- MACINTOSH: `applemac`, Mac OS Roman.

Not text, so none: a byte the encoding leaves undefined (Windows-1252's five
holes, which iconv refuses) and a C1 control (ISO 8859-15's 0x80–0x9F). Two
rows from the encoding's owner rather than from glibc (`ownerRows`): Apple's
own table (VENDORS/APPLE/ROMAN.TXT, which the WHATWG index-macintosh
follows) maps 0xC6 to U+2206 INCREMENT, where glibc keeps the older
U+0394 GREEK CAPITAL LETTER DELTA, and 0xF0 to U+F8FF, the Apple logo,
where glibc spells a private-use scalar of its own (U+E01E). Apple's table
is the one read throughout, 0xDB's euro sign included, where pdfLaTeX's
applemac.def keeps the table as it stood before 1998 and spells some bytes
by the nearest LaTeX command; the decoding module lists them beside its
rule.
-/

def die (msg : String) : IO α := do
  IO.eprintln msg
  IO.Process.exit 1

/-- The scalar iconv decodes one byte of `charset` to, or none where it
refuses the byte. -/
def iconvByte (dir : System.FilePath) (charset : String) (b : UInt8) : IO (Option Nat) := do
  let path := dir / "byte"
  IO.FS.writeBinFile path ⟨#[b]⟩
  let out ← try
      IO.Process.output { cmd := "iconv", args := #["-f", charset, "-t", "UTF-8", path.toString] }
    catch _ => die "iconv not found; it decodes the encodings"
  if out.exitCode != 0 then return none
  match out.stdout.toList with
  | [c] => return some c.toNat
  | _ => return none

def isC1 (v : Nat) : Bool := 0x80 ≤ v && v ≤ 0x9F

/-- The rows an encoding's owner maps differently from glibc, by charset:
byte and scalar. -/
def ownerRows : List (String × UInt8 × Nat) :=
  [("MACINTOSH", 0xC6, 0x2206), ("MACINTOSH", 0xF0, 0xF8FF)]

def hex4 (v : Nat) : String :=
  let digits := Nat.toDigits 16 v
  String.ofList (List.replicate (4 - digits.length) '0' ++ digits) |>.toUpper

def rowLit : Option Nat → String
  | some v => s!"some '\\u{hex4 v}'"
  | none => "none"

def main : IO UInt32 := do
  let version ← try
      pure ((← IO.Process.output { cmd := "iconv", args := #["--version"] }).stdout.splitOn "\n"
        |>.headD "").trimAscii.toString
    catch _ => die "iconv not found; it decodes the encodings"
  let encodings : List (String × String × String) := [
    ("windows1252", "WINDOWS-1252",
      "Windows-1252, read for `latin1`, `ansinew` and `cp1252`."),
    ("iso885915", "ISO-8859-15", "ISO 8859-15, read for `latin9`."),
    ("macRoman", "MACINTOSH", "Mac OS Roman, read for `applemac`.")]
  let (defs, counts) ← IO.FS.withTempDir fun dir => do
    let mut defs : Array String := #[]
    let mut counts : Array String := #[]
    for (name, charset, doc) in encodings do
      let mut rows : Array (Option Nat) := #[]
      for k in [0:128] do
        let b : UInt8 := UInt8.ofNat (0x80 + k)
        let v ← iconvByte dir charset b
        let v := match ownerRows.find? fun (cs, byte, _) => cs == charset && byte == b with
          | some (_, _, owner) => some owner
          | none => v
        rows := rows.push (match v with
          | some v => if isC1 v || v ≥ 0x110000 || (0xD800 ≤ v && v ≤ 0xDFFF) then none else some v
          | none => none)
      let defined := (rows.filter (·.isSome)).size
      if defined < 96 then
        die s!"{charset}: only {defined} of 128 bytes decoded; iconv changed shape"
      counts := counts.push s!"{name} {defined}"
      let lits := rows.toList.map rowLit
      let lines := (List.range 22).map fun r => String.intercalate ", " ((lits.drop (6 * r)).take 6)
      let body := String.intercalate ",\n    " lines
      defs := defs.push s!"/-- {doc}
Entry `k` is byte `0x80 + k`. -/
public def {name} : Array (Option Char) :=
  #[{body}]"
    return (defs, counts)
  let out := s!"module

/-
Generated by scripts/gen-encoding-data.lean; do not edit by hand. Regenerate with:
  lake env lean --run scripts/gen-encoding-data.lean

Source: {version}, one byte at a time, with the generator's two
rows from the encoding's owner (Mac OS Roman 0xC6 and 0xF0). Each table is an
encoding's upper half: the scalar each byte from 0x80 stands for, none where
the encoding has no character. This module carries only data: `Encoding.Legacy.high`
reads it, and its contracts are checked by the suite.
-/

namespace LeanTex.Core.EncodingData

{String.intercalate "\n\n" defs.toList}

end LeanTex.Core.EncodingData
"
  IO.FS.writeFile "LeanTex/Core/EncodingData.lean" out
  IO.println s!"wrote LeanTex/Core/EncodingData.lean: \
{String.intercalate ", " counts.toList} bytes defined"
  return 0
